### ISSUE TITLE
Unable to access website

### ISSUE THREAD

**Issue by ZGStuff** [woozier/woogedownload#8]
hey i know that you guys are busy, but i wanna get on woogedownload and i cant it just shows "check if there is a typo in woogedownload.billygoat891.tk". any reason why?????

**Comment by ghost** [comment]
not a bug
billygoat891 deleted the domain

**Comment by ZGStuff** [comment]
aw

**Comment by ghost** [comment]
> aw

I mean, who cared about it anyway. Just some crappy & cringy site.
